---
- hosts: all
  user: root

  tasks:

  - set_fact:
        my_pass: "{{ pwd }}"

  - name: Adcionar Usuarios charles 
    user:
     name: charles.a 
     password: "{{ my_pass }}"
     state: present
     shell: /bin/bash
     update_password: on_create
     system: no  
     createhome: yes    
     home: /home/charles.a
