---
- hosts: all 
  user: root
  connection: ssh
  #become_user: root
  #become: yes
  #become_method: sudo
  #connection: paramiko
  gather_facts: true 

  vars:

     pwd: "{{ lookup('password', '/dev/null length=17 chars=ascii_letters') }}"
     chave_dir_ori: ../chaves
     chave_arq_ori: charles.a.pub

  tasks:

  - set_fact:
        my_pass: "{{ pwd }}"

  - name: Adcionar Usuarios charles 
    user:
     name: charles.a 
     password: "{{ my_pass }}"
     state: present
     shell: /bin/bash
     update_password: on_create
     system: no  
     createhome: yes    
     home: /home/charles.a

  - name: Set up authorized_keys for the deploy user
    authorized_key: 
      user=charles.a
      key="{{ lookup('file', '{{ chave_dir_ori }}/{{ chave_arq_ori }}') }}"

  - name: Add user to sudoers file
    lineinfile:
     backup: yes
     path: /etc/sudoers
     regexp: '^charles.a'
     line: 'charles.a  ALL=(ALL) NOPASSWD: ALL'
     validate: 'visudo -cf %s'



