---
- hosts: all
  user: root
  
  vars: 
     chave_dir_ori: /Users/charles.a/Acessos/Ansible/chaves
     chave_arq_ori: charles.a.pub
     chave_dir_dst:  ~/.ssh
     chave_arq_dst: authorized_keys
     pwd: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"

  tasks:

  - set_fact:
        my_pass: "{{ pwd }}"

  - name: Adcionar Usuarios charles 
    user:
     name: charles.a 
     password: "{{ my_pass }}"
     state: present
     shell: /bin/bash
     update_password: on_create
     system: no  
     createhome: yes    
     home: /home/charles.a
