---
- hosts: all 
  user: charles.a 
  connection: ssh
  become_user: root
  become: yes
  become_method: sudo
  connection: paramiko

  vars:
     ntpdate_server: pool.ntp.br

  tasks:
     - name: Execute ntpdate runs
       command: "ntpdate -s {{ ntpdate_server|default('0.pool.ntp.org') }}"

     - debug: var=ansible_date_time

     - debug: msg="the current date is {{ ansible_date_time.time }}"
