---
- hosts: all
  user: charles.a
  connection: ssh
  become_user: root
  become: yes
  become_method: sudo
  connection: paramiko

  tasks:
      - debug: var=ansible_date_time

      - debug: msg="the current date is {{ ansible_date_time.time }}"
